name: Run python only unit tests

on:
  push:
  workflow_dispatch:

jobs:
  run-python-tests:
    runs-on: ubuntu-latest
    name: Run python only unit tests
    steps:
      - uses: SuffolkLITLab/ALActions/pythontests@main